name: "PR Labeler"

on:
  pull_request_target:
    types: ["opened", "reopened", "ready_for_review"]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594  # v4
    if: ${{ github.event.pull_request.draft == false }}